org: forhad
app: aws-python-1
service: aws-python-1

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  region: us-east-1

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
